FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}

COPY src/main/resources/sql/* /docker-entrypoint-initdb.d/

EXPOSE 3306

# Build like this:
# docker build  -f Dockerfile.mysql -t mysql-server .

# Run like this:
# docker network create projectmanagement || true
# docker run -it --rm --name mysql-server -p 3306:3306 --network adventurexp -e MYSQL_ROOT_PASSWORD=password123 mysql-server